Navbar yenilendi
msgsumatematik/msgsumatematik.github.io pull request #5
Opened 2023-10-25 09:58 UTC by ibulutx

2023-10-26 07:53 UTC, habipakyol approved these changes
Looks good, thanks!

2023-10-27 18:56 UTC, sadikkuzu requested changes
index.html'deki navbar çok güzel olmuş, eline sağlık 👏🏼 

![image](https://github.com/msgsumatematik/msgsumatematik.github.io/assets/23168063/0bd8b033-22ad-4d9b-bb0e-4ef8088f9317)

Galeri sayfasında da benzer navbar yapabilir misin?

![image](https://github.com/msgsumatematik/msgsumatematik.github.io/assets/23168063/0f460d49-6688-437b-ad0e-d87b257d94c0)

2023-11-03 16:18 UTC, sadikkuzu commented
@ibulutx @musolee1 selam, buraya review girmiştim.

2023-11-03 19:15 UTC, yusufelyldrm commented
Tüm sayfalarda aynı url'i mi kullanalım? @ibulutx

2023-11-09 21:52 UTC, closed without merging